//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "employeeterritories")]
pub struct Model {
    pub employeeid: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub territoryid: Option<String>,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::employees::Entity",
        from = "Column::Employeeid",
        to = "super::employees::Column::Employeeid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Employees,
    #[sea_orm(
        belongs_to = "super::territories::Entity",
        from = "Column::Territoryid",
        to = "super::territories::Column::Territoryid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Territories,
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::territories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Territories.def()
    }
}
