//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod categories;
pub mod customers;
pub mod employees;
pub mod employeeterritories;
pub mod order_details;
pub mod orders;
pub mod products;
pub mod regions;
pub mod shippers;
pub mod suppliers;
pub mod territories;
pub mod users;
