//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub orderid: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub customerid: Option<String>,
    pub employeeid: Option<i64>,
    pub orderdate: Option<DateTimeWithTimeZone>,
    pub requireddate: Option<DateTimeWithTimeZone>,
    pub shippeddate: Option<DateTimeWithTimeZone>,
    pub shipvia: Option<i64>,
    pub freight: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shipname: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shipaddress: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shipcity: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shipregion: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shippostalcode: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shipcountry: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_details::Entity")]
    OrderDetails,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::Customerid",
        to = "super::customers::Column::Customerid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::employees::Entity",
        from = "Column::Employeeid",
        to = "super::employees::Column::Employeeid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Employees,
    #[sea_orm(
        belongs_to = "super::shippers::Entity",
        from = "Column::Shipvia",
        to = "super::shippers::Column::Shipperid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Shippers,
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetails.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::shippers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shippers.def()
    }
}
