//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::categories::Entity as Categories;
pub use super::customers::Entity as Customers;
pub use super::employees::Entity as Employees;
pub use super::employeeterritories::Entity as Employeeterritories;
pub use super::order_details::Entity as OrderDetails;
pub use super::orders::Entity as Orders;
pub use super::products::Entity as Products;
pub use super::regions::Entity as Regions;
pub use super::shippers::Entity as Shippers;
pub use super::suppliers::Entity as Suppliers;
pub use super::territories::Entity as Territories;
pub use super::users::Entity as Users;
